/***********************************************************************************************************************
 *
 * names
 * a simple list of random names to choose from
 *
 **********************************************************************************************************************/

/*
 * SHIP CLASS NAMES
 */
const SHIP_CLASS_NAMES = [
    "Farragut",
    "Porter",
    "Mahan",
    "Gridley",
    "Bagley",
    "Somers",
    "Benham",
    "Sims",
    "Gleaves",
    "Benson",
    "Fletcher",
    "Allen M. Sumner",
    "Gearing",
    "Caldwell",
    "Wickes",
    "Clemson",
    "Bainbridge",
    "Truxtun",
    "Smith",
    "Paulding",
    "Cassin",
    "Aylwin",
    "O'Brien",
    "Tucker",
    "Sampson",
    "Mitscher",
    "Forrest Sherman",
    "Farragut",
    "Charles F. Adams",
    "Spruance",
    "Kidd",
    "Arleigh Burke",
    "Zumwalt",
    "Daring",
    "Havock",
    "Ferret",
    "Ardent",
    "Charger",
    "Hardy",
    "Janus",
    "Salmon",
    "Banshee",
    "Fervent",
    "Conflict",
    "Handy",
    "Sunfish",
    "Rocket",
    "Sturgeon",
    "Swordfish",
    "Zebra",
    "Quail",
    "Earnest",
    "Spiteful",
    "Myrmidon",
    "Star",
    "Avon",
    "Brazen",
    "Violet",
    "Mermaid",
    "Gipsy",
    "Bullfinch",
    "Fawn",
    "Falcon",
    "Greyhound",
    "Thorn",
    "Hawthorn",
    "Thornycroft",
    "Armstrong-Whitworth",
    "Lampo",
    "Nembo",
    "Soldato",
    "Indomito",
    "Ardito",
    "Audace",
    "Rosolino Pilo",
    "Alessandro Poerio",
    "Aquila",
    "Mirabello",
    "La Masa",
    "Giuseppe Sirtori",
    "Palestro",
    "Generali",
    "Curtatone",
    "Leone",
    "Sella",
    "Sauro",
    "Turbine or Borea",
    "Navigatori",
    "Freccia or Dardo",
    "Folgore",
    "Maestrale",
    "Oriani",
    "Soldati",
    "Leningrad",
    "Tashkent",
    "Gnevny",
    "Soobrazitelnyy",
    "Opytny",
    "Ognevoy",
    "Zhivushiy",
    "Likhoy",
    "Legky",
    "Prytky",
    "Prochny",
    "Soldati",
    "Skoryy",
    "Neustrashimy",
    "Kotlin",
    "Kildin",
    "Krupny",
    "Kashin",
    "Sovremennyy",
    "Udaloy",
    "Sokol",
    "Hǎi Lóng",
    "Kit",
    "Forel",
    "Som",
    "Buinyi",
    "Groznyi",
    "Leitenant Pushchin",
    "Leitenant Burakov",
    "Tverdyi",
    "Kapitan Yurasovskiy",
    "Deyatelnyi",
    "Finn",
    "Vsadnik",
    "Okhotnik",
    "Ukrayna",
    "Leitenant Shestakov",
    "Novik",
    "Ragnar",
    "Hugin",
    "Wrangel",
    "Ehrenskold",
    "Klas",
    "Göteborg",
    "Psilander",
    "Romulus",
    "Mode",
    "Visby",
    "Oland",
    "Halland",
    "Östergotland",
    "Gloire",
    "Warrior",
    "Magenta",
    "Formidabile",
    "Provence",
    "Principe di Carignano",
    "Re d'Italia",
    "Regina Maria Pia",
    "Pervenets",
    "Roma",
    "Océan",
    "Cerberus",
    "Audacious",
    "Swiftsure",
    "Devastation",
    "Principe Amedeo",
    "Superb",
    "Colbert",
    "Caio Duilio",
    "Belleisle",
    "Ajax",
    "Dévastation",
    "Italia",
    "Conqueror",
    "Terrible",
    "Dingyuan",
    "Admiral",
    "Amiral Baudin",
    "Ruggiero di Lauria",
    "Colossus",
    "Ekaterina II",
    "Victoria",
    "Marceau",
    "Imperator Aleksandr II",
    "Re Umberto",
    "Trafalgar",
    "Royal Sovereign",
    "Centurion",
    "Brandenburg",
    "Evertsen",
    "Petropavlovsk",
    "Monarch",
    "Indiana",
    "Majestic",
    "Charlemagne",
    "Fuji",
    "Ammiraglio di Saint Bon",
    "Kaiser Friedrich III",
    "Shikishima",
    "Peresvet",
    "Canopus",
    "Kearsarge",
    "Illinois",
    "Habsburg",
    "Borodino",
    "Regina Margherita",
    "Virginia",
    "Formidable",
    "Maine",
    "Wittelsbach",
    "République",
    "King Edward VII",
    "Duncan",
    "Swiftsure",
    "Erzherzog Karl",
    "Liberté",
    "Braunschweig",
    "Regina Elena",
    "Katori",
    "Connecticut",
    "Evstafi",
    "Andrei Pervozvanny",
    "Mississippi",
    "Nassau",
    "Lord Nelson",
    "Bellerophon",
    "Danton",
    "Radetzky",
    "Kawachi",
    "St. Vincent",
    "South Carolina",
    "Reşadiye",
    "Minas Geraes",
    "Satsuma",
    "Delaware",
    "Neptune",
    "Colossus",
    "Florida",
    "Courbet",
    "Helgoland",
    "Gangut",
    "Imperatritsa Mariya",
    "Kaiser",
    "Orion",
    "Wyoming",
    "King George V",
    "Tegetthoff",
    "Andrea Doria",
    "España",
    "König",
    "Iron Duke",
    "New York",
    "Rivadavia",
    "Bretagne",
    "Almirante Latorre",
    "Fusō",
    "Conte di Cavour",
    "Queen Elizabeth",
    "Revenge",
    "Nevada",
    "Pennsylvania",
    "Ise",
    "New Mexico",
    "Tennessee",
    "Nagato",
    "Colorado",
    "Nelson",
    "Dunkerque",
    "Scharnhorst",
    "Littorio",
    "Richelieu",
    "Bismarck",
    "King George V",
    "North Carolina",
    "Yamato",
    "South Dakota",
    "Iowa",
    "Pará",
    "Marcilio Dias",
    "Jurua",
    "Acre",
    "Pará",
    "Mato Grosso",
    "Marcilio Dias",
    "Pará",
    "Niki",
    "Thyella",
    "Wild Beast",
    "Kriti",
    "Keravnos",
    "Hydra",
    "Vasilefs Georgios",
    "Salamis",
    "Navarinon",
    "Adrias",
    "Doxa",
    "Wild Beast",
    "Sfnedoni",
    "Hatakaze",
    "Kongō",
    "Murasame",
    "Takanami",
    "Atago",
    "Akizuki",
    "Teniente Rodríguez",
    "Almirante Guise",
    "Almirante Villar",
    "Villar",
    "Palacios",
    "Garcia y Garcia",
    "Colonel Bolognesi",
    "Wicher",
    "Grom",
    "Garland",
    "Piorun",
    "Orkan",
    "Hunt",
    "Wicher",
    "Warszawa"
];

/*
 * SHIP NAMES
 * TODO: add popular scifi ships
 */
const SHIP_NAMES = [
    // USN destroyers
    "Clemson",
    "Dahlgren",
    "Goldsborough",
    "Semmes",
    "Satterlee",
    "Mason",
    "Graham",
    "Abel P. Upshur",
    "Hunt",
    "Welborn C. Wood",
    "George E. Badger",
    "Branch",
    "Herndon",
    "Alexander Dallas",
    "Chandler",
    "Southard",
    "Hovey",
    "Long",
    "Broome",
    "Alden",
    "Smith Thompson",
    "Barker",
    "Tracy",
    "Borie",
    "John D. Edwards",
    "Whipple",
    "Parrott",
    "Edsall",
    "MacLeish",
    "Simpson",
    "Bulmer",
    "McCormick",
    "Stewart",
    "Pope",
    "Peary",
    "Pillsbury",
    "John D. Ford",
    "Truxtun",
    "Paul Jones",
    "Hatfield",
    "Brooks",
    "Gilmer",
    "Fox",
    "Kane",
    "Humphreys",
    "McFarland",
    "James K. Paulding",
    "Overton",
    "Sturtevant",
    "Childs",
    "King",
    "Sands",
    "Williamson",
    "Reuben James",
    "Bainbridge",
    "Goff",
    "Barry",
    "Hopkins",
    "Lawrence",
    "Belknap",
    "McCook",
    "McCalla",
    "Rodgers",
    "Osmond Ingram",
    "Bancroft",
    "Welles",
    "Aulick",
    "Turner",
    "Gillis",
    "Delphy",
    "McDermut",
    "Laub",
    "McLanahan",
    "Edwards",
    "GreeneAnthony",
    "Ballard",
    "Shubrick",
    "Bailey",
    "Thornton",
    "Morris",
    "Tingey",
    "Swasey",
    "Meade",
    "Sinclair",
    "McCawley",
    "Moody",
    "Henshaw",
    "Meyer",
    "Doyen",
    "Sharkey",
    "Toucey",
    "Breck",
    "Isherwood",
    "Case",
    "Lardner",
    "Putnam",
    "Worden",
    "Flusser",
    "Dale",
    "Converse",
    "Reid",
    "Billingsley",
    "Charles Ausburn",
    "Osborne",
    "Chauncey",
    "Fuller",
    "Percival",
    "John Francis Burnes",
    "Farragut",
    "Somers",
    "Stoddert",
    "Reno",
    "Farquhar",
    "Thompson",
    "Kennedy",
    "Paul Hamilton",
    "William Jones",
    "Woodbury",
    "S. P. Lee",
    "Nicholas",
    "Young",
    "Zeilin",
    "Yarborough",
    "La Vallette",
    "Sloat",
    "Wood",
    "Shirk",
    "Kidder",
    "Selfridge",
    "Marcus",
    "Mervine",
    "Chase",
    "Robert Smith",
    "Mullany",
    "Coghlan",
    "Preston",
    "Lamson",
    "Bruce",
    "Hull",
    "Macdonough",
    "Farenholt",
    "Sumner",
    "Corry",
    "Melvin",
    "Litchfield",
    "Zane",
    "Wasmuth",
    "Trever",
    "Perry",
    "Decatur",
    "Hulbert",
    "Noa",
    "William B. Preston",
    "Preble",
    "Sicard",
    "Pruitt",
    "Gearing",
    "Eugene A. Greene",
    "Gyatt",
    "Kenneth D. Bailey",
    "William R. Rush",
    "William M. Wood",
    "Wiltsie",
    "Theodore E. Chandler",
    "Hamner",
    "Epperson",
    "Frank Knox",
    "Southerland",
    "William C. Lawe",
    "Lloyd Thomas",
    "Keppler",
    "Rowan",
    "Gurke",
    "McKean",
    "Henderson",
    "Richard B. Anderson",
    "James E. Kyes",
    "Hollister",
    "Eve",
    "James E. Kyes",
    "Hollister",
    "Eversole",
    "Shelton",
    "Chevalier",
    "Higbee",
    "Benner",
    "Dennis J. Buckley",
    "Corry",
    "New",
    "Holder",
    "Rich",
    "Johnston",
    "Robert H. McCard",
    "Samuel B. Roberts",
    "Basilone",
    "Carpenter",
    "Agerholm",
    "Robert A. Owens",
    "Timmerman",
    "Myles C. Fox",
    "Everett F. Larson",
    "Goodrich",
    "Hanson",
    "Herbert J. Thomas",
    "Turner",
    "Charles P. Cecil",
    "George K. MacKenzie",
    "Sarsfield",
    "Ernest G. Small",
    "Power",
    "Glennon",
    "Noa",
    "Fiske",
    "Warrington",
    "Perry",
    "Bausell",
    "Ozbourn",
    "Robert L. Wilson",
    "Witek",
    "Richard E. Kraus",
    "Joseph P. Kennedy Jr.",
    "Rupertus",
    "Leonard F. Mason",
    "Charles H. Roan",
    "Fred T. Berry",
    "Norris",
    "McCaffery",
    "Harwood",
    "Vogelgesang",
    "Steinaker",
    "Harold J. Ellison",
    "Charles R. Ware",
    "Cone",
    "Stribling",
    "Brownson",
    "Arnold J. Isbell",
    "Fechteler",
    "Damato",
    "Forrest Royal",
    "Hawkins",
    "Duncan",
    "Henry W. Tucker",
    "Rogers",
    "Perkins",
    "Vesole",
    "Leary",
    "Dyess",
    "Bordelon",
    "Furse",
    "Newman K. Perry",
    "Floyd B. Parks",
    "John R. Craig",
    "Orleck",
    "Brinkley Bass",
    "Stickell",
    "O'Hare",
    "Meredith",
    /*
     * culture ship names
     * https://en.wikipedia.org/wiki/List_of_spacecraft_in_the_Culture_series
     */
    "Bora Horza Gobuchul",
    "Determinist",
    "Eschatologist (temporary name)",
    "Irregular Apocalypse",
    "No More Mr Nice Guy",
    "Profit Margin",
    "Nervous Energy",
    "Prosthetic Conscience",
    "Revisionist",
    "Trade Surplus",
    "The Ends Of Invention",
    "The Hand of God 137",
    "Clear Air Turbulence or 'CAT' for short",
    "Control Surface",
    "Cargo Cult",
    "Little Rascal",
    "So Much For Subtlety",
    "Unfortunate Conflict Of Evidence",
    "Youthful Indiscretion",
    "Flexible Demeanour",
    "Just Read The Instructions",
    "Of Course I Still Love You",
    "Zealot",
    "Limiting Factor",
    "Gunboat Diplomat",
    "Kiss My Ass",
    "Prime Mover",
    "Screw Loose",
    "Invincible",
    "Bad For Business",
    "Ablation",
    "Arbitrary",
    "Arrested Development",
    "A Series Of Unlikely Explanations",
    "A Ship With A View",
    "Big Sexy Beast",
    "Boo!",
    "Cantankerous",
    "Credibility Problem",
    "Dramatic Exit",
    "Excuses And Accusations",
    "Funny, It Worked Last Time...",
    "God Told Me To Do It",
    "Halation Effect",
    "Happy Idiot Talk ",
    "Helpless In The Face Of Your Beauty",
    "Heresiarch",
    "I Thought He Was With You",
    "It'll Be Over By Christmas",
    "Just Another Victim Of The Ambient Morality",
    "Minority Report",
    "Never Talk To Strangers",
    "Not Wanted On Voyage",
    "Only Slightly Bent",
    "Perfidy",
    "Sacrificial Victim",
    "Space Monster",
    "Stranger Here Myself",
    "Synchronize Your Dogmas",
    "Thank You And Goodnight",
    "The Precise Nature Of The Catastrophe",
    "Ultimate Ship The Second",
    "Undesirable Alien",
    "Unwitting Accomplice",
    "Well I Was In The Neighbourhood",
    "You'll Thank Me Later",
    "You Would If You Really Loved Me",
    "Congenital Optimist",
    "Size Isn't Everything",
    "What Are The Civilian Applications?",
    "Just Testing",
    "Sweet and Full of Grace",
    "Very Little Gravitas Indeed",
    "Xenophobe",
    "Anticipation Of A New Lover's Arrival, The",
    "Death And Gravity",
    "Ethics Gradient",
    "Honest Mistake",
    "Limivorous",
    "Uninvited Guest",
    "Use Psychology",
    "What Is The Answer And Why?",
    "Wisdom Like Silence",
    "Yawning Angel",
    "Zero Gravitas",
    "Not Invented Here",
    "Misophist",
    "Serious Callers Only",
    "Steely Glint",
    "Different Tan",
    "Fate Amenable To Change",
    "Grey Area (aka Meatfucker)",
    "It's Character Forming",
    "Jaundiced Outlook",
    "Problem Child",
    "Reasonable Excuse",
    "Recent Convert",
    "Tactical Grace",
    "Unacceptable Behaviour",
    "Attitude Adjuster",
    "Heavy Messing",
    "Killing Time",
    "Frank Exchange Of Views",
    "T3OU 4",
    "T3OU 118",
    "T3OU 736",
    "Charitable View",
    "Just Passing Through",
    "I Blame My Mother",
    "I Blame Your Mother",
    "Full Refund (formerly MBU 604)",
    "Quietly Confident",
    "No Fixed Abode",
    "Highpoint",
    "Shoot Them Later",
    "Appeal To Reason",
    "Break Even",
    "Long View",
    "Peace Makes Plenty",
    "Sober Counsel",
    "Within Reason",
    "Frightspear",
    "Furious Purpose",
    "Kiss The Blade",
    "Riptalon",
    "SacSlicer II",
    "Wingclipper",
    "Xenoclast",
    "Experiencing A Significant Gravitas Shortfall",
    "Lasting Damage",
    "Lasting Damage I",
    "Lasting Damage II",
    "Sanctioned Parts List",
    "Grey Area (aka Meatfucker)",
    "Nuisance Value",
    "Resistance Is Character-Forming",
    "Vulgarian",
    "Someone Else's Problem",
    "Lacking That Small Match Temperament",
    "Poke It With A Stick",
    "I Said, I've Got A Big Stick",
    "Hand Me The Gun And Ask Me Again",
    "But Who's Counting?",
    "Germane Riposte",
    "We Haven't Met But You're A Great Fan Of Mine",
    "All The Same, I Saw It First",
    "Ravished By The Sheer Implausibility Of That Last Statement",
    "Zero Credibility",
    "Charming But Irrational",
    "Demented But Determined",
    "You May Not Be The Coolest Person Here",
    "Lucid Nonsense",
    "Awkward Customer",
    "Thorough But... Unreliable",
    "Advanced Case Of Chronic Patheticism",
    "Another Fine Product From The Nonsense Factory",
    "Conventional Wisdom",
    "In One Ear",
    "Fine Till You Came Along",
    "I Blame The Parents",
    "Inappropriate Response",
    "A Momentary Lapse Of Sanity",
    "Lapsed Pacifist",
    "Reformed Nice Guy",
    "Pride Comes Before A Fall",
    "Injury Time",
    "Now Look What You've Made Me Do",
    "Kiss This Then",
    "Winter Storm",
    "Piety",
    "Soulhaven",
    "Seed Drill",
    "Don't Try This At Home",
    "Xenoglossicist",
    "Subtle Shift In Emphasis",
    "Experiencing A Significant Gravitas Shortfall",
    "It's My Party And I'll Sing If I Want To",
    "Lightly Seared On The Reality Grill",
    "Pure Big Mad Boat Man",
    "Qualifier",
    "Transient Atmospheric Phenomenon",
    "You Naughty Monsters",
    "Eight Rounds Rapid",
    "You'll Clean That Up Before You Leave",
    "Now We Try It My Way",
    "Liveware Problem",
    "Now, Turning to Reason, & its Just Sweetness",
    "On First Seeing Jhiriit",
    "Fasilyce, Upon Waking",
    "Inspiral, Coalescence, Ringdown",
    "Hence the Fortress",
    "Hundredth Idiot, The",
    "Dressed Up To Party",
    "Pelagian",
    "Sense Amid Madness, Wit Amidst Folly",
    "Total Internal Reflection",
    "Armchair Traveller",
    "Bodhisattva, OAQS",
    "Falling Outside The Normal Moral Constraints",
    "No One Knows What The Dead Think",
    "Hylozoist",
    "The Usual But Etymologically Unsatisfactory",
    "Beastly To The Animals",
    "Fixed Grin",
    "Hidden Income",
    "Scar Glamour",
    "Labtebricolephile",
    "Me, I'm Counting",
    "Messenger Of Truth",
    "Fractious Person",
    "Rubric Of Ruin",
    "Abundance Of Onslaught",
    "Vision Of Hope Surpassed",
    "Joiler Veppers (provisional name)",
    "Ucalegon",
    "8401.00 Partial Photic Boundary",
    "A Fine Disregard For Awkward Facts",
    "Contents May Differ",
    "Empiricist",
    "Just The Washing Instruction Chip In Life's Rich Tapestry",
    "Kakistocrat",
    "Teething Problems",
    "Unreliable Witness",
    "Passing By And Thought I'd Drop In",
    "Pressure Drop",
    "You Call This Clean?",
    "Displacement Activity",
    "Warm, Considering",
    "Anything Legal Considered",
    "Beats Working",
    "Headcrash",
    "Questionable Ethics",
    "Xenocrat",
    "Caconym",
    "New Toy",
    "Rapid Random Response Unit",
    "Learned Response",
    "Outstanding Contribution To The Historical Process",
    "Refreshingly Unconcerned With The Vulgar Exigencies Of Veracity",
    "Value Judgement",
    "Zoologist",
    "Mistake Not…",
    "Smile Tolerantly",
    "Gelish-Oplule",
    "Uagren",
    "Churkun",
    "Iberre",
    "CH2OH.(CHOH)4.CHO",
    "Abalule-Sheliz",
    "Gellemtyan-Asool-Anafawaya",
    "Laskuil-Hliz",
    "Quiatrea-Anang",
    "Fulanya-Guang",
    "Melancholia Enshrines All Triumph",
    "Oceanic Dissonance",
    "Exaltation-Parsimony III"
];


/*
 * helper functions that return a random name.
 */
const randomShipClassName = () => {
    return SHIP_CLASS_NAMES[Math.floor(Math.random() * SHIP_CLASS_NAMES.length - 1)];
};
const randomShipName = () => {
    return SHIP_NAMES[Math.floor(Math.random() * SHIP_NAMES.length - 1)];
};

module.exports = {randomShipClassName, randomShipName};
